### ISSUE TITLE
marco crashes with SIGABRT at meta_ui_get_default_window_icon() on FreeBSD (ui/ui.c:854)

### ISSUE THREAD

**Issue by douglas-carmichael** [mate-desktop/marco#181]
I have a MATE 1.8.1 installation on FreeBSD 10.1-RELEASE (with marco 1.8.2) and marco coredumps with a SIGABRT every time I start my session (from xdm) but then eventually does still start.

When I did a gdb backtrace, it crashes on meta_ui_get_default_window_icon() on line 854 of ui.c.

What could cause this?

Here is the backtrace:
---
```
(gdb) where

#0  0x000000080539a6ca in thr_kill () from /lib/libc.so.7

#1  0x000000080546f149 in abort () from /lib/libc.so.7

#2  0x0000000803ccb487 in g_assertion_message () from /usr/local/lib/libglib-2.0.so.0

#3  0x0000000803ccb4ee in g_assertion_message_expr ()

   from /usr/local/lib/libglib-2.0.so.0

#4  0x000000000049cbbd in meta_ui_get_default_window_icon (ui=0x80a0e2300)

    at ui/ui.c:854

#5  0x0000000000439c01 in get_fallback_icons (screen=0x80a0dddc0, iconp=0x7fffffffdef0, 

    ideal_width=32, ideal_height=32, mini_iconp=0x7fffffffdee8, ideal_mini_width=16, 

    ideal_mini_height=16) at core/iconcache.c:45

#6  0x0000000000439115 in meta_read_icons (screen=0x80a0dddc0, xwindow=6291494, 

    icon_cache=0x80a13be68, wm_hints_pixmap=0, wm_hints_mask=0, iconp=0x7fffffffdef0, 

    ideal_width=32, ideal_height=32, mini_iconp=0x7fffffffdee8, ideal_mini_width=16, 

    ideal_mini_height=16) at core/iconcache.c:824

#7  0x000000000045cc2f in meta_window_update_icon_now (window=0x80a13be00)

    at core/window.c:5848

#8  0x000000000045be52 in meta_window_new_with_attrs (display=0x80a1f9400, 

    xwindow=6291494, must_be_viewable=1, attrs=0x80a10efc8) at core/window.c:609

#9  0x0000000000449c9b in meta_screen_manage_all_windows (screen=0x80a0dddc0)

    at core/screen.c:776

#10 0x00000000004248b4 in meta_display_open () at core/display.c:745

#11 0x000000000044146b in main (argc=1, argv=0x7fffffffeb58) at core/main.c:591

(gdb) where 4

#0  0x000000080539a6ca in thr_kill () from /lib/libc.so.7

#1  0x000000080546f149 in abort () from /lib/libc.so.7

#2  0x0000000803ccb487 in g_assertion_message () from /usr/local/lib/libglib-2.0.so.0

#3  0x0000000803ccb4ee in g_assertion_message_expr ()

   from /usr/local/lib/libglib-2.0.so.0

----
```

**Comment by monsta** [comment]
@stefano-k: can you please edit it to use Markdown? It references a lot of unrelated issues now...

Also this issue is fixed by https://github.com/mate-desktop/marco/pull/177.
