### ISSUE TITLE
marco (gtk3) crashes with some metacity themes

### ISSUE THREAD

**Issue by NiceandGently** [mate-desktop/marco#205]
opening mate-appearance-properties causes a abrt alarm which pointed to marco.
stacktrace:
```
Thread 1 (Thread 0x7f46d0dd8a00 (LWP 2339)):
#0  0x00007f46cb593a98 in __GI___libc_sigaction (sig=2339, act=0x923, oact=0x6) at ../sysdeps/unix/sysv/linux/x86_64/sigaction.c:54
        result = <optimized out>
        kact = {k_sa_handler = 0x7f46d0df4840, sa_flags = 140725531631552, sa_restorer = 0x100000000, sa_mask = {__val = {140725531631536, 252833149, 139942045244075, 4294967295, 139942036386552, 139942035873096, 21543808, 117, 139942048547680, 140725531631920, 139942081571520, 18540032, 139942036068138, 32, 0, 0}}}
        koact = {k_sa_handler = 0x0, sa_flags = 0, sa_restorer = 0x0, sa_mask = {__val = {0, 0, 0, 0, 0, 0, 0, 0, 0, 21543808, 117, 139942048547680, 139942126636496, 117, 139942048547680, 140725531631920}}}
#1  0x00007f46cb5e2e9c in __GI___libc_free (ptr=0x85, str=0x7f46cb6e9808 "munmap_chunk(): invalid pointer", action=21543808) at malloc.c:4973
        buf = "\200\273H\001\000\000\000\000\350D\337\320F\177\000\000\n"
        cp = <optimized out>
        p = 0x75
        size = <optimized out>
        block = <optimized out>
        total_size = <optimized out>
        ar_ptr = <optimized out>
        p = 0x75
        hook = <optimized out>
#2  0x00007f46cb5e2e9c in __GI___libc_free (p=0x75) at malloc.c:2823
        p = 0x75
        size = <optimized out>
        block = <optimized out>
        total_size = <optimized out>
        ar_ptr = <optimized out>
        p = 0x75
        hook = <optimized out>
#3  0x00007f46cb5e2e9c in __GI___libc_free (mem=0x85) at malloc.c:2948
        ar_ptr = <optimized out>
        p = 0x75
        hook = <optimized out>
#4  0x00007f46ce0f698d in  () at /usr/lib64/libmarco-private.so.0
#5  0x00007f46ce0f90a8 in  () at /usr/lib64/libmarco-private.so.0
#6  0x0000000000000523 in  ()
#7  0x00007f46ce0faac0 in __FUNCTION__.54826 () at /usr/lib64/libmarco-private.so.0
#8  0x00007f46cbeb333a in g_assertion_message_expr (domain=0x10 <error: Cannot access memory at address 0x10>, domain@entry=0x7f46ce0f698d "marco", file=0x7f46ce0fa050 "spec->data.gtk.state < N_GTK_STATES", file@entry=0x7f46ce0f90a8 "ui/theme.c", line=-873442894, line@entry=1315, func=0x38e00609a9b23d00 <error: Cannot acPython Exception <class 'TypeError'> iter() returned non-iterator of type '_iterator': 
cess memory at address 0x38e00609a9b23d00>, func@entry=0x7f46ce0faac0 <__FUNCTION__.54826> "meta_color_spec_new_from_string", expr=expr@entry=0x7f46ce0fa050 "spec->data.gtk.state < N_GTK_STATES") at gtestutils.c:2371
        s = 0x38e00609a9b23d00 <error: Cannot access memory at address 0x38e00609a9b23d00>
#9  0x00007f46ce0f6265 in meta_color_spec_new_from_string (str=<optimized out>, err=err@entry=0x7ffd3752e390) at ui/theme.c:1315
        tmp = <optimized out>
        state = GTK_STATE_FLAG_INSENSITIVE
        component = META_GTK_COLOR_BG
        bracket = <optimized out>
        end_bracket = <optimized out>
        spec = 0x122c070
        __FUNCTION__ = "meta_color_spec_new_from_string"
#10 0x00007f46ce0f6339 in meta_color_spec_new_from_string (str=str@entry=0x1233e70 "shade/gtk:bg[INSENSITIVE]/1.1", err=err@entry=0x7ffd3752e390) at ui/theme.c:1432
        split = 0x1246ed0
        factor = 1.1000000000000001
        end = 0x122c053 ""
        base = 0x0
        spec = 0x0
        __FUNCTION__ = "meta_color_spec_new_from_string"
#11 0x00007f46ce0e5679 in parse_color (theme=<optimized out>, str=0x1233e70 "shade/gtk:bg[INSENSITIVE]/1.1", err=err@entry=0x7ffd3752e390) at ui/theme-parser.c:788
        referent = 0x1180e50 "color"
#12 0x00007f46ce0eaebd in start_element_handler (error=0x7ffd3752e390, info=0x7ffd3752e480, attribute_values=0x7ffd3752e320, attribute_names=<optimized out>, element_name=0x1180e50 "color", context=0x11ae600) at ui/theme-parser.c:2802
        value = 0x1233e70 "shade/gtk:bg[INSENSITIVE]/1.1"
        color_spec = <optimized out>
        info = 0x7ffd3752e480
#13 0x00007f46ce0eaebd in start_element_handler (context=0x11ae600, element_name=<optimized out>, attribute_names=<optimized out>, attribute_values=0x7ffd3752e320, user_data=0x7ffd3752e480, error=0x7ffd3752e390) at ui/theme-parser.c:3458
        info = 0x7ffd3752e480
#14 0x00007f46cbe90013 in emit_start_element (context=context@entry=0x11ae600, error=error@entry=0x7ffd3752e550) at gmarkup.c:1049
        i = <optimized out>
        j = <optimized out>
        start_name = <optimized out>
        attr_names = 0x7ffd3752e340
        attr_values = 0x7ffd3752e320
        tmp_error = 0x0
#15 0x00007f46cbe911a3 in g_markup_parse_context_parse (context=context@entry=0x11ae600, text=<optimized out>, text_len=<optimized out>, error=error@entry=0x7ffd3752e550) at gmarkup.c:1396
        __func__ = "g_markup_parse_context_parse"
#16 0x00007f46ce0e5954 in load_theme (theme_dir=theme_dir@entry=0x149a760 "/usr/share/themes/Metabox/metacity-1", theme_name=theme_name@entry=0x1186ed0 "Metabox", major_version=major_version@entry=1, error=error@entry=0x7ffd3752e550) at ui/theme-parser.c:4084
        context = 0x11ae600
        info = {states = 0x1199a40, theme_name = 0x1186ed0 "Metabox", theme_file = 0x133b9f0 "/usr/share/themes/Metabox/metacity-1/metacity-theme-1.xml", theme_dir = 0x149a760 "/usr/share/themes/Metabox/metacity-1", theme = 0x126cad0, format_version = 1, name = 0x0, layout = 0x0, op_list = 0x11dc810, op = 0x12c8e90, style = 0x0, style_set = 0x0, piece = META_FRAME_PIECE_LAST, button_type = META_BUTTON_TYPE_LAST, button_state = META_BUTTON_STATE_LAST}
        text = 0x14e4040 "<?xml version=\"1.0\"?>\n<metacity_theme>\n\t<info>\n\t\t<name>Metabox</name>\n\t\t<author>Garrett LeSage &lt;garrett@redhat.com&gt; based on Havoc Pennington &lt;hp@redhat.com&gt;'s Atlanta theme</author>\n\t\t<co"...
        length = 19955
        theme_filename = 0x11a7ff0 "metacity-theme-1.xml"
        theme_file = 0x133b9f0 "/usr/share/themes/Metabox/metacity-1/metacity-theme-1.xml"
        retval = 0x0
        __FUNCTION__ = "load_theme"
#17 0x00007f46ce0ec920 in meta_theme_load (theme_name=0x1186ed0 "Metabox", err=0x0) at ui/theme-parser.c:4190
        error = 0x0
        theme_dir = 0x149a760 "/usr/share/themes/Metabox/metacity-1"
        retval = 0x0
        xdg_data_dirs = 0x0
        version = 1
        i = <optimized out>
#18 0x0000000000421f14 in message_from_capplet (theme_thumbnail_data=0x7ffd3752eba0) at theme-thumbnail.c:354
        window = 0x7f46cbed2400
        align = <optimized out>
        allocation = {x = -870722304, y = 32582, width = -870727492, height = 32582}
        theme = 0x11612a0
        pixbuf = 0x8
        icon_width = 0
        icon_height = 0
        region = 0x7ffd3752e621
        vbox = 0x7f46cbe7ba63
        vbox_allocation = {x = 18462912, y = 0, width = 18151120, height = 0}
        icon = 0x114f6d0 [y:	window: %ld  x,y: %d %d	w,h: %d %d  b-w: %d  parent: %ld	 ovr: %d]
        box = <optimized out>
        radio = <optimized out>
        flags = (META_FRAME_ALLOWS_DELETE | META_FRAME_ALLOWS_MENU | META_FRAME_ALLOWS_MINIMIZE | META_FRAME_ALLOWS_MAXIMIZE | META_FRAME_ALLOWS_VERTICAL_RESIZE | META_FRAME_ALLOWS_HORIZONTAL_RESIZE | META_FRAME_HAS_FOCUS | META_FRAME_ALLOWS_SHADE | META_FRAME_ALLOWS_MOVE)
        preview = <optimized out>
        stock_button = <optimized out>
        checkbox = <optimized out>
        requisition = {width = 19594480, height = 0}
        pixbuf = 0x0
        i = <optimized out>
        rowstride = <optimized out>
        type = <optimized out>
        pixels = <optimized out>
        width = -870722304
        height = 18462912
        source = <optimized out>
        condition = <optimized out>
        data = 0x7ffd3752eba0
        buffer = "marco\000\000\000Metabox\000\000Sans 10\000\250I\001", '\000' <repeats 12 times>, "\001\000\000\000\000\000\000\000\360\374*\001\000\000\000\000\320\366\024\001\000\000\000\000\000\325\031\314F\177\000\000\234.^\313F\177\000\000\001\000\000\200\000\000\000\000c\272\347\313F\177\000\000[\000\000\000n\000\000\000d\244\352\313F\177\000\000\020\251I\001\000\000\000\000\300\270\031\001", '\000' <repeats 12 times>, "d\244\352\313F\177\000\000\360\374*\001\000\000\000\000\000\244F\001\000\000\000\000p\t\030\001\000\000\000\000\000\244F\001\000\000\000\000\340W\030\001\000\000\000\000p\342\033\001\000\000\000\000\000\220\027\001\000\000\000\000"...
        status = <optimized out>
        bytes_read = 25
        theme_thumbnail_data = 0x7ffd3752eba0
#19 0x0000000000421f14 in message_from_capplet (source=<optimized out>, condition=<optimized out>, data=0x7ffd3752eba0) at theme-thumbnail.c:681
        pixbuf = 0x0
        i = <optimized out>
        rowstride = <optimized out>
        type = <optimized out>
        pixels = <optimized out>
        width = -870722304
        height = 18462912
        source = <optimized out>
        condition = <optimized out>
        data = 0x7ffd3752eba0
        buffer = "marco\000\000\000Metabox\000\000Sans 10\000\250I\001", '\000' <repeats 12 times>, "\001\000\000\000\000\000\000\000\360\374*\001\000\000\000\000\320\366\024\001\000\000\000\000\000\325\031\314F\177\000\000\234.^\313F\177\000\000\001\000\000\200\000\000\000\000c\272\347\313F\177\000\000[\000\000\000n\000\000\000d\244\352\313F\177\000\000\020\251I\001\000\000\000\000\300\270\031\001", '\000' <repeats 12 times>, "d\244\352\313F\177\000\000\360\374*\001\000\000\000\000\000\244F\001\000\000\000\000p\t\030\001\000\000\000\000\000\244F\001\000\000\000\000\340W\030\001\000\000\000\000p\342\033\001\000\000\000\000\000\220\027\001\000\000\000\000"...
        status = <optimized out>
        bytes_read = 25
        theme_thumbnail_data = 0x7ffd3752eba0
#20 0x00007f46cbe8ca8a in g_main_context_dispatch (context=0x116af80) at gmain.c:3122
        dispatch = 0x7f46cbed2400 <g_io_unix_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x7ffd3752eba0
        callback = 0x421350 <draw_window_on_pixbuf+352>
        cb_funcs = 0x7f46cc17b8a0 <g_source_callback_funcs>
        cb_data = 0x118fd70
        need_destroy = <optimized out>
        source = 0x11914a0
        current = 0x114b1c0
        i = 0
#21 0x00007f46cbe8ca8a in g_main_context_dispatch (context=context@entry=0x116af80) at gmain.c:3737
#22 0x00007f46cbe8ce20 in g_main_context_iterate (context=0x116af80, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3808
        max_priority = 2147483647
        timeout = 14907
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 4
        fds = 0x118fd20
#23 0x00007f46cbe8d142 in g_main_loop_run (loop=0x112a8e0) at gmain.c:4002
        __func__ = "g_main_loop_run"
#24 0x00007f46cd9f2255 in post_parse_hook (context=<optimized out>, group=<optimized out>, data=0x112a8e0, error=0x422da0 <wm_common_register_window_manager_change+112>) at gtkmain.c:773
        display_name = 0x0
        context = <optimized out>
        group = <optimized out>
        data = 0x112a8e0
        error = 0x422da0 <wm_common_register_window_manager_change+112>
        info = 0x112a8e0
#25 0x0000000100000014 in  ()
#26 0x00007f4600000007 in  ()
#27 0x000000000115e360 in  ()
#28 0x000000000115e390 in  ()
#29 0x000000000118fa10 in  ()
#30 0x000000000118fa40 in  ()
#31 0x000000000118fa70 in  ()
#32 0x000000000118faa0 in  ()
#33 0x38e00609a9b23d00 in  ()
#34 0x0000000000000000 in  ()
From                To                  Syms Read   Shared Object Library
```
The crash is cause by /usr/share/themes/Metabox/metacity-1/metacity-theme-1.xml from metacity.
metacity and mutter does not have the g_assert (spec->data.gtk.state < N_GTK_STATES);
see 
https://git.gnome.org/browse/mutter/commit/?id=28deea44d45808c846fa674d80497ee6408a3e6f
https://git.gnome.org/browse/metacity/commit/?id=c9099b4a90932a22c86b960c8b4dc7cd1458defe

So, adopt this to marco should fix the issue.
This is also reproducable with Mist theme from gnome-themes.
full stacktrace https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/metacity-theme-backtrace

**Comment by infirit** [comment]
Should be fixed with #206 which I merged just now.
