### ISSUE TITLE
marco crashes when you turn compositing off

### ISSUE THREAD

**Issue by monsta** [mate-desktop/marco#226]
Using Debian Testing with marco built from git master.

Steps to reproduce:
```$ gsettings set org.mate.Marco.general compositing-manager true```
```$ gsettings set org.mate.Marco.general compositing-manager false```

Then marco crashes:
```
Program received signal SIGSEGV, Segmentation fault.
repair_display (display=0x2626c70) at compositor/compositor-xrender.c:1371
1371	  if (compositor->repaint_id > 0)
(gdb) bt full
#0  0x00000000004154c7 in compositor_idle_cb (display=0x2626c70) at compositor/compositor-xrender.c:1371
Python Exception <class 'TypeError'> iter() returned non-iterator of type '_iterator': 
        screens = 0x26b5960
        compositor = 0x2626c70
        compositor = <optimized out>
#1  0x00000000004154c7 in compositor_idle_cb (data=<optimized out>) at compositor/compositor-xrender.c:1389
        compositor = <optimized out>
#2  0x00007f52b5292e9a in g_main_context_dispatch (context=0x25df800) at /build/glib2.0-BMd9vh/glib2.0-2.46.0/./glib/gmain.c:3154
        dispatch = 0x7f52b528f950 <g_idle_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x2717fb0
        callback = 0x415480 <compositor_idle_cb>
        cb_funcs = <optimized out>
        cb_data = 0x26dcee0
        need_destroy = <optimized out>
        source = 0x26cb880
        current = 0x270f3c0
        i = 0
#3  0x00007f52b5292e9a in g_main_context_dispatch (context=context@entry=0x25df800) at /build/glib2.0-BMd9vh/glib2.0-2.46.0/./glib/gmain.c:3769
#4  0x00007f52b5293240 in g_main_context_iterate (context=0x25df800, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/glib2.0-BMd9vh/glib2.0-2.46.0/./glib/gmain.c:3840
        max_priority = 100
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 4
        fds = 0x270ab00
#5  0x00007f52b5293562 in g_main_loop_run (loop=0x25e0290) at /build/glib2.0-BMd9vh/glib2.0-2.46.0/./glib/gmain.c:4034
        __func__ = "g_main_loop_run"
#6  0x000000000040f691 in main (argc=1, argv=0x7fff225316b8) at core/main.c:579
        act = 
          {__sigaction_handler = {sa_handler = 0x42b8f0 <sigterm_handler>, sa_sigaction = 0x42b8f0 <sigterm_handler>}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x770000006e}
        empty_mask = {__val = {0 <repeats 16 times>}}
        meta_args = 
          {save_file = 0x0, display_name = 0x0, client_id = 0x25e0310 "\004", replace_wm = <optimized out>, disable_sm = 0, print_version = <optimized out>, sync = <optimized out>, composite = <optimized out>, no_composite = <optimized out>, no_force_fullscreen = <optimized out>}
        log_domains = 
          {0x0, 0x46c3f6 "marco", 0x469dfa "Gtk", 0x469dfe "Gdk", 0x469e02 "GLib", 0x469e07 "Pango", 0x469e0d "GLib-GObject", 0x469e1a "GThread"}
        i = <optimized out>
        channel = <optimized out>
(gdb)
```

**Comment by monsta** [comment]
Ok, ```git bisect``` told me the regression has been introduced in https://github.com/mate-desktop/marco/commit/b53fb913abe7da1e8d56bd50151f673c90cf121d.

**Comment by raveit65** [comment]
For me it looks like that https://github.com/mate-desktop/marco/commit/b53fb913abe7da1e8d56bd50151f673c90cf121d needs more work.

**Comment by monsta** [comment]
I'll remove that commit from 1.10 branch for now, we surely don't need any regressions there.

**Comment by bl0ckeduser** [comment]
looks like a subtle timing bug.  it crashes because compositor is NULL, so maybe a NULL check would do the job. but I am having trouble reproducing #27 with a new build of marco, it completely stops drawing shadows now.

**Comment by monsta** [comment]
Yes, I've also noticed that tooltips for tray icons of GTK+3 apps (e.g. nm-applet) don't have shadows. I guess we can safely revert that commit then.
