### ISSUE TITLE
Marco crash

### ISSUE THREAD

**Issue by vistad** [mate-desktop/marco#651]
#### unexpected full system crash - the bug report:
===================================================================
 Info                                                              
===================================================================
           PID: 1849 (marco)
           UID: 1000 (victor)
           GID: 1000 (victor)
        Signal: 11 (SEGV)
     Timestamp: Fri 2020-09-25 14:06:28 MSK (46min ago)
  Command Line: marco --composite --replace
    Executable: /usr/bin/marco
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (victor)
       Boot ID: 85b44e7d64b3458b81826692560a8d6b
    Machine ID: 2e6db7b3feeb408ba59f7482257bc249
      Hostname: san-mateo
       Storage: /var/lib/systemd/coredump/core.marco.1000.85b44e7d64b3458b81826692560a8d6b.1849.1601031988000000000000.lz4
       Message: Process 1849 (marco) of user 1000 dumped core.
                
                Stack trace of thread 1849:
                #0  0x00007feab4d0c655 meta_frame_get_frame_bounds (libmarco-private.so.2 + 0x3a655)
                #1  0x00007feab4d2fd6d meta_window_get_frame_bounds (libmarco-private.so.2 + 0x5dd6d)
                #2  0x00007feab4cfb930 n/a (libmarco-private.so.2 + 0x29930)
                #3  0x00007feab4cfcb1e n/a (libmarco-private.so.2 + 0x2ab1e)
                #4  0x00007feab4cfcc28 n/a (libmarco-private.so.2 + 0x2ac28)
                #5  0x00007feab4dcee8e g_main_context_dispatch (libglib-2.0.so.0 + 0x51e8e)
                #6  0x00007feab4dcf240 n/a (libglib-2.0.so.0 + 0x52240)
                #7  0x00007feab4dcf533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #8  0x0000555c0e900233 main (marco + 0x3233)
                #9  0x00007feab4b070b3 __libc_start_main (libc.so.6 + 0x270b3)
                #10 0x0000555c0e90064e n/a (marco + 0x364e)
                
                Stack trace of thread 1858:
                #0  0x00007feab4bf5aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007feab4dcf1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007feab4dcf2e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007feab253e99d n/a (libdconfsettings.so + 0xa99d)
                #4  0x00007feab4df8931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007feab4a53609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007feab4c02293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 1857:
                #0  0x00007feab4bf5aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007feab4dcf1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007feab4dcf2e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007feab4dcf331 n/a (libglib-2.0.so.0 + 0x52331)
                #4  0x00007feab4df8931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007feab4a53609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007feab4c02293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 1859:
                #0  0x00007feab4bf5aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007feab4dcf1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007feab4dcf533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007feab3eddeda n/a (libgio-2.0.so.0 + 0x11eeda)
                #4  0x00007feab4df8931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007feab4a53609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007feab4c02293 __clone (libc.so.6 + 0x122293)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 1849]
[New LWP 1858]
[New LWP 1857]
[New LWP 1859]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `marco --composite --replace'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007feab4d0c655 in meta_frame_get_frame_bounds () from /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
[Current thread is 1 (Thread 0x7feab2b20a80 (LWP 1849))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 1849]
[New LWP 1858]
[New LWP 1857]
[New LWP 1859]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `marco --composite --replace'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007feab4d0c655 in meta_frame_get_frame_bounds () from /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
[Current thread is 1 (Thread 0x7feab2b20a80 (LWP 1849))]
#0  0x00007feab4d0c655 in meta_frame_get_frame_bounds () at /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
#1  0x00007feab4d2fd6d in meta_window_get_frame_bounds () at /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
#2  0x00007feab4cfb930 in  () at /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
#3  0x00007feab4cfcb1e in  () at /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
#4  0x00007feab4cfcc28 in  () at /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
#5  0x00007feab4dcee8e in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007feab4dcf240 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007feab4dcf533 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x0000555c0e900233 in main ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 1849]
[New LWP 1858]
[New LWP 1857]
[New LWP 1859]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `marco --composite --replace'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007feab4d0c655 in meta_frame_get_frame_bounds () from /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
[Current thread is 1 (Thread 0x7feab2b20a80 (LWP 1849))]

Thread 4 (Thread 0x7feab152a700 (LWP 1859)):
#0  0x00007feab4bf5aff in __GI___poll (fds=0x7feaa4016e50, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007feab4dcf1ae in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007feab4dcf533 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007feab3eddeda in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007feab4df8931 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007feab4a53609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140645974058752, 1641469095620600069, 140645982447630, 140645982447631, 140645982447776, 140645974056064, -1652036187403099899, -1652044565481430779}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007feab4c02293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7feab252c700 (LWP 1857)):
#0  0x00007feab4bf5aff in __GI___poll (fds=0x555c0ec95b30, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007feab4dcf1ae in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007feab4dcf2e3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007feab4dcf331 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007feab4df8931 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007feab4a53609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140645990844160, 1641469095620600069, 140724117236478, 140724117236479, 140724117236624, 140645990841472, -1652029589259591419, -1652044565481430779}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007feab4c02293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7feab1d2b700 (LWP 1858)):
#0  0x00007feab4bf5aff in __GI___poll (fds=0x555c0ec97ad0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007feab4dcf1ae in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007feab4dcf2e3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007feab253e99d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007feab4df8931 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007feab4a53609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140645982451456, 1641469095620600069, 140724117236862, 140724117236863, 140724117237008, 140645982448768, -1652037286377856763, -1652044565481430779}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007feab4c02293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7feab2b20a80 (LWP 1849)):
#0  0x00007feab4d0c655 in meta_frame_get_frame_bounds () at /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
#1  0x00007feab4d2fd6d in meta_window_get_frame_bounds () at /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
#2  0x00007feab4cfb930 in  () at /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
#3  0x00007feab4cfcb1e in  () at /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
#4  0x00007feab4cfcc28 in  () at /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
#5  0x00007feab4dcee8e in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007feab4dcf240 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007feab4dcf533 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x0000555c0e900233 in main ()
#0  0x00007feab4d0c655 in meta_frame_get_frame_bounds () at /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
#1  0x00007feab4d2fd6d in meta_window_get_frame_bounds () at /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
#2  0x00007feab4cfb930 in  () at /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
#3  0x00007feab4cfcb1e in  () at /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
#4  0x00007feab4cfcc28 in  () at /usr/lib/x86_64-linux-gnu/libmarco-private.so.2
#5  0x00007feab4dcee8e in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007feab4dcf240 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007feab4dcf533 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x0000555c0e900233 in main ()

**Comment by vistad** [comment]
A full system crash - nothing like that happened for a few years. I had to shutdown with REISUBO

**Comment by raveit65** [comment]
Thank you for linking other bugreports with your numbers in your stacktrace.
We can't revert that.
Please quote stacktraces or terminal outputs.
