### ISSUE TITLE
Marco crash: All window title bars sometimes disappear, reboot then required

### ISSUE THREAD

**Issue by hottwaj** [mate-desktop/marco#691]
#### Expected behaviour
Window title bars should not disappear!

#### Actual behaviour
Occasionally title bars for all windows disappear, all windows become immovable & not resizable, and the window list in the panel stops working.

The contents of windows themselves continue to work, as does the "Menu/Start" button in the bottom panel.

#### Steps to reproduce the behaviour
This crash appears to occur randomly with no obvious trigger and has probably happened to me about 10 times in total over a couple months of use. Sometimes it has happened immediately after log in (as soon as I start programs that use windows), other times it happens after system has been up for a while and I'm using number of windows.

#### MATE general version
1.24.0-2 

#### Package version
(Not sure how this differs from MATE general version above?)

#### Linux Distribution
Linux Mint 20.2

#### Link to bugreport of your Distribution (requirement)
https://forums.linuxmint.com/viewtopic.php?f=206&t=354845

### Crash report

See stacktrace from Marco that I found in system reports - happened around the same time I most recently had this issue
```
===================================================================
 Info                                                              
===================================================================
           PID: 6921 (marco)
           UID: 1000 (jonathan)
           GID: 1000 (jonathan)
        Signal: 11 (SEGV)
     Timestamp: Tue 2021-08-10 09:11:54 BST (22min ago)
  Command Line: marco --composite --replace
    Executable: /usr/bin/marco
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (jonathan)
       Boot ID: f36baa22ed814e2496cc8af804ca5b16
    Machine ID: 2a4b02270e3742148865b3f7bd5aa46f
      Hostname: rampage-hp2
       Storage: /var/lib/systemd/coredump/core.marco.1000.f36baa22ed814e2496cc8af804ca5b16.6921.1628583114000000000000.lz4
       Message: Process 6921 (marco) of user 1000 dumped core.
                
                Stack trace of thread 6921:
                #0  0x00007fbbd3e009d4 cairo_region_num_rectangles (libcairo.so.2 + 0x659d4)
                #1  0x00007fbbd4acc41e n/a (libmarco-private.so.2 + 0x2741e)
                #2  0x00007fbbd4ace944 n/a (libmarco-private.so.2 + 0x29944)
                #3  0x00007fbbd4acfb1e n/a (libmarco-private.so.2 + 0x2ab1e)
                #4  0x00007fbbd4acfc28 n/a (libmarco-private.so.2 + 0x2ac28)
                #5  0x00007fbbd4ba204e g_main_context_dispatch (libglib-2.0.so.0 + 0x5204e)
                #6  0x00007fbbd4ba2400 n/a (libglib-2.0.so.0 + 0x52400)
                #7  0x00007fbbd4ba26f3 g_main_loop_run (libglib-2.0.so.0 + 0x526f3)
                #8  0x00005563979c8233 main (marco + 0x3233)
                #9  0x00007fbbd48da0b3 __libc_start_main (libc.so.6 + 0x270b3)
                #10 0x00005563979c864e n/a (marco + 0x364e)
                
                Stack trace of thread 6927:
                #0  0x00007fbbd49c8aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007fbbd4ba236e n/a (libglib-2.0.so.0 + 0x5236e)
                #2  0x00007fbbd4ba24a3 g_main_context_iteration (libglib-2.0.so.0 + 0x524a3)
                #3  0x00007fbbd4ba24f1 n/a (libglib-2.0.so.0 + 0x524f1)
                #4  0x00007fbbd4bcbad1 n/a (libglib-2.0.so.0 + 0x7bad1)
                #5  0x00007fbbd4826609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fbbd49d5293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 6929:
                #0  0x00007fbbd49c8aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007fbbd4ba236e n/a (libglib-2.0.so.0 + 0x5236e)
                #2  0x00007fbbd4ba24a3 g_main_context_iteration (libglib-2.0.so.0 + 0x524a3)
                #3  0x00007fbbd237399d n/a (libdconfsettings.so + 0xa99d)
                #4  0x00007fbbd4bcbad1 n/a (libglib-2.0.so.0 + 0x7bad1)
                #5  0x00007fbbd4826609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fbbd49d5293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 6928:
                #0  0x00007fbbd49c8aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007fbbd4ba236e n/a (libglib-2.0.so.0 + 0x5236e)
                #2  0x00007fbbd4ba26f3 g_main_loop_run (libglib-2.0.so.0 + 0x526f3)
                #3  0x00007fbbd3cb0f8a n/a (libgio-2.0.so.0 + 0x11ef8a)
                #4  0x00007fbbd4bcbad1 n/a (libglib-2.0.so.0 + 0x7bad1)
                #5  0x00007fbbd4826609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fbbd49d5293 __clone (libc.so.6 + 0x122293)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 6921]
[New LWP 6927]
[New LWP 6929]
[New LWP 6928]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `marco --composite --replace'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fbbd3e009d4 in cairo_region_num_rectangles () from /lib/x86_64-linux-gnu/libcairo.so.2
[Current thread is 1 (Thread 0x7fbbd28f1a80 (LWP 6921))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 6921]
[New LWP 6927]
[New LWP 6929]
[New LWP 6928]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `marco --composite --replace'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fbbd3e009d4 in cairo_region_num_rectangles () from /lib/x86_64-linux-gnu/libcairo.so.2
[Current thread is 1 (Thread 0x7fbbd28f1a80 (LWP 6921))]
#0  0x00007fbbd3e009d4 in cairo_region_num_rectangles () at /lib/x86_64-linux-gnu/libcairo.so.2
#1  0x00007fbbd4acc41e in  () at /lib/x86_64-linux-gnu/libmarco-private.so.2
#2  0x00007fbbd4ace944 in  () at /lib/x86_64-linux-gnu/libmarco-private.so.2
#3  0x00007fbbd4acfb1e in  () at /lib/x86_64-linux-gnu/libmarco-private.so.2
#4  0x00007fbbd4acfc28 in  () at /lib/x86_64-linux-gnu/libmarco-private.so.2
#5  0x00007fbbd4ba204e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007fbbd4ba2400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007fbbd4ba26f3 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00005563979c8233 in main ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 6921]
[New LWP 6927]
[New LWP 6929]
[New LWP 6928]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `marco --composite --replace'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fbbd3e009d4 in cairo_region_num_rectangles () from /lib/x86_64-linux-gnu/libcairo.so.2
[Current thread is 1 (Thread 0x7fbbd28f1a80 (LWP 6921))]

Thread 4 (Thread 0x7fbbcf9df700 (LWP 6928)):
#0  0x00007fbbd49c8aff in __GI___poll (fds=0x556398806600, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007fbbd4ba236e in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fbbd4ba26f3 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fbbd3cb0f8a in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007fbbd4bcbad1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fbbd4826609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140444618848000, -606938868563073096, 140736614562126, 140736614562127, 140736614562272, 140444618845312, 640680388673120184, 640656100970571704}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fbbd49d5293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fbbcf191700 (LWP 6929)):
#0  0x00007fbbd49c8aff in __GI___poll (fds=0x556398813050, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007fbbd4ba236e in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fbbd4ba24a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fbbd237399d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007fbbd4bcbad1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fbbd4826609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140444610139904, -606938868563073096, 140736614565150, 140736614565151, 140736614565296, 140444610137216, 640679251580528568, 640656100970571704}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fbbd49d5293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fbbd01e0700 (LWP 6927)):
#0  0x00007fbbd49c8aff in __GI___poll (fds=0x5563987f1bc0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007fbbd4ba236e in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fbbd4ba24a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fbbd4ba24f1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fbbd4bcbad1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fbbd4826609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140444627240704, -606938868563073096, 140736614561694, 140736614561695, 140736614561840, 140444627238016, 640663896535574456, 640656100970571704}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fbbd49d5293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fbbd28f1a80 (LWP 6921)):
#0  0x00007fbbd3e009d4 in cairo_region_num_rectangles () at /lib/x86_64-linux-gnu/libcairo.so.2
#1  0x00007fbbd4acc41e in  () at /lib/x86_64-linux-gnu/libmarco-private.so.2
#2  0x00007fbbd4ace944 in  () at /lib/x86_64-linux-gnu/libmarco-private.so.2
#3  0x00007fbbd4acfb1e in  () at /lib/x86_64-linux-gnu/libmarco-private.so.2
#4  0x00007fbbd4acfc28 in  () at /lib/x86_64-linux-gnu/libmarco-private.so.2
#5  0x00007fbbd4ba204e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007fbbd4ba2400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007fbbd4ba26f3 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00005563979c8233 in main ()
#0  0x00007fbbd3e009d4 in cairo_region_num_rectangles () at /lib/x86_64-linux-gnu/libcairo.so.2
#1  0x00007fbbd4acc41e in  () at /lib/x86_64-linux-gnu/libmarco-private.so.2
#2  0x00007fbbd4ace944 in  () at /lib/x86_64-linux-gnu/libmarco-private.so.2
#3  0x00007fbbd4acfb1e in  () at /lib/x86_64-linux-gnu/libmarco-private.so.2
#4  0x00007fbbd4acfc28 in  () at /lib/x86_64-linux-gnu/libmarco-private.so.2
#5  0x00007fbbd4ba204e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007fbbd4ba2400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007fbbd4ba26f3 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00005563979c8233 in main ()
```

### System info

```
System:    Kernel: 5.11.0-25-generic x86_64 bits: 64 compiler: N/A Desktop: MATE 1.24.0 wm: marco 
           dm: LightDM Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 
Machine:   Type: Convertible System: HP product: HP Spectre x360 Convertible 14-ea0xxx v: N/A 
           serial: <filter> Chassis: type: 31 serial: <filter> 
           Mobo: HP model: 87F6 v: 40.49 serial: <filter> UEFI: AMI v: F.11 date: 04/23/2021 
Battery:   ID-1: BAT0 charge: 62.7 Wh condition: 63.4/66.5 Wh (95%) volts: 8.8/7.7 
           model: HP Primary serial: <filter> status: Charging 
           Device-1: hid-0018:04F3:2BF1.0001-battery model: ELAN2514:00 04F3:2BF1 serial: N/A 
           charge: N/A status: N/A 
           Device-2: hid-17:08:85:e0:28:92-battery model: Bluetooth 3.0 Keyboard serial: N/A 
           charge: N/A status: Discharging 
CPU:       Topology: Quad Core model: 11th Gen Intel Core i7-1165G7 bits: 64 type: MT MCP 
           arch: Tiger Lake rev: 1 L2 cache: 12.0 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 44851 
           Speed: 4100 MHz min/max: 400/4700 MHz Core speeds (MHz): 1: 4241 2: 3890 3: 4338 
           4: 3967 5: 3631 6: 3783 7: 4298 8: 4105 
Graphics:  Device-1: Intel vendor: Hewlett-Packard driver: i915 v: kernel bus ID: 0000:00:02.0 
           chip ID: 8086:9a49 
           Display: x11 server: X.Org 1.20.11 driver: modesetting unloaded: fbdev,vesa 
           compositor: marco resolution: 1920x1280~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel Xe Graphics (TGL GT2) v: 4.6 Mesa 21.0.3 
           direct render: Yes 
Audio:     Device-1: Intel vendor: Hewlett-Packard driver: sof-audio-pci bus ID: 0000:00:1f.3 
           chip ID: 8086:a0c8 
           Sound Server: ALSA v: k5.11.0-25-generic 
Network:   Device-1: Intel driver: iwlwifi v: kernel port: 3000 bus ID: 0000:00:14.3 
           chip ID: 8086:a0f0 
           IF: wlo1 state: up mac: <filter> 
Drives:    Local Storage: total: 476.94 GiB used: 471.22 GiB (98.8%) 
           ID-1: /dev/nvme0n1 model: KXG60ZNV512G KIOXIA size: 476.94 GiB speed: 31.6 Gb/s 
           lanes: 4 serial: <filter> 
RAID:      Hardware-1: Intel Volume Management Device NVMe RAID Controller driver: vmd v: 0.6 
           bus ID: 0000:00:0e.0 chip ID: 8086.9a0b 
Partition: ID-1: / size: 36.42 GiB used: 16.02 GiB (44.0%) fs: ext4 dev: /dev/nvme0n1p5 
           ID-2: swap-1 size: 29.80 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/nvme0n1p7 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 1 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 4 rev: 3.1 chip ID: 1d6b:0003 
           Hub: 3-0:1 info: Full speed (or root) Hub ports: 12 rev: 2.0 chip ID: 1d6b:0002 
           Device-1: 3-5:2 info: Quanta HP True Vision HD Camera type: Video driver: uvcvideo 
           rev: 2.0 chip ID: 0408:5442 
           Device-2: 3-9:3 info: Elan Micro ELAN:ARM-M4 type: <vendor specific> driver: N/A 
           rev: 2.0 chip ID: 04f3:0c4c 
           Device-3: 3-10:4 info: Intel type: Bluetooth driver: btusb rev: 2.0 chip ID: 8087:0026 
           Hub: 4-0:1 info: Full speed (or root) Hub ports: 4 rev: 3.1 chip ID: 1d6b:0003 
Sensors:   System Temperatures: cpu: 67.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list 
           1: deb https: //dl.winehq.org/wine-builds/ubuntu/ focal main
           2: deb [arch=amd64] https: //download.virtualbox.org/virtualbox/debian focal contrib
           Active apt repos in: /etc/apt/sources.list.d/cappelikan-ppa-focal.list 
           1: deb http: //ppa.launchpad.net/cappelikan/ppa/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/gezakovacs-ppa-focal.list 
           1: deb http: //ppa.launchpad.net/gezakovacs/ppa/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/graphics:darktable.list 
           1: deb http: //download.opensuse.org/repositories/graphics:/darktable/xUbuntu_20.04/ /
           Active apt repos in: /etc/apt/sources.list.d/jetbrains-ppa.list 
           1: deb http: //jetbrains-ppa.s3-website.eu-central-1.amazonaws.com focal main
           Active apt repos in: /etc/apt/sources.list.d/jonaski-strawberry-focal.list 
           1: deb http: //ppa.launchpad.net/jonaski/strawberry/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/kxstudio-debian-ppas.list 
           1: deb http: //ppa.launchpad.net/kxstudio-debian/libs/ubuntu bionic main
           2: deb http: //ppa.launchpad.net/kxstudio-debian/music/ubuntu bionic main
           3: deb http: //ppa.launchpad.net/kxstudio-debian/plugins/ubuntu bionic main
           4: deb http: //ppa.launchpad.net/kxstudio-debian/apps/ubuntu bionic main
           5: deb http: //ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu bionic main
           Active apt repos in: /etc/apt/sources.list.d/kxstudio-external.list 
           1: deb [arch=amd64,i386] https: //kx.studio/repo/ stable free
           2: deb [arch=amd64,i386] https: //kx.studio/repo/ gcc5 free
           Active apt repos in: /etc/apt/sources.list.d/libreoffice-ppa-focal.list 
           1: deb http: //ppa.launchpad.net/libreoffice/ppa/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/linuxuprising-shutter-focal.list 
           1: deb http: //ppa.launchpad.net/linuxuprising/shutter/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/lutris-team-lutris-focal.list 
           1: deb http: //ppa.launchpad.net/lutris-team/lutris/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/nodesource.list 
           1: deb [signed-by=/usr/share/keyrings/nodesource.gpg] https: //deb.nodesource.com/node_14.x focal main
           2: deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https: //deb.nodesource.com/node_14.x focal main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //www.mirrorservice.org/sites/packages.linuxmint.com/packages uma main upstream import backport
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/slimbook-slimbook-focal.list 
           1: deb http: //ppa.launchpad.net/slimbook/slimbook/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/spotify.list 
           1: deb http: //repository.spotify.com stable non-free
           Active apt repos in: /etc/apt/sources.list.d/steam.list 
           1: deb [arch=amd64,i386] https: //repo.steampowered.com/steam/ stable steam
           2: deb-src [arch=amd64,i386] https: //repo.steampowered.com/steam/ stable steam
Info:      Processes: 299 Uptime: 18m Memory: 15.29 GiB used: 2.19 GiB (14.3%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 10.3.0 alt: 10/9 Client: Unknown python3.8 client 
           inxi: 3.0.38 
```

### Notes

I use Chrome which has its own "special title bar" (not system title bar).  Not sure if that is somehow related or not

Thanks!

**Comment by hottwaj** [comment]
p.s. in case it is relevant, this is on a Tiger Lake based laptop CPU/GPU.  Until May 2021 I was using a laptop with a Skylake CPU/GPU (and Linux Mint 20.1 + Mate) and don't remember having this issue.  Thanks!

**Comment by hottwaj** [comment]
Hmm looks like this is probably the same issue as in: #617

**Comment by hottwaj** [comment]
Will close assuming this is the same as #617, I've tried upgrading to 1.24.1 (via package for newer version of ubuntu than I am using: https://launchpad.net/ubuntu/+source/marco/1.24.2-0ubuntu1), hopefully will not see this issue anymore.  Thanks!
